# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationC', models.IntegerField(primary_key=True, serialize=False)),
                ('Stname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tinfo',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ordn0', models.IntegerField()),
                ('sA', models.TimeField(blank=True)),
                ('aD', models.TimeField(blank=True)),
                ('A', models.TimeField(blank=True)),
                ('D', models.TimeField(blank=True)),
                ('late', models.TimeField(blank=True)),
                ('stationC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trno', models.IntegerField(primary_key=True, serialize=False)),
                ('trname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tinfo',
            name='trno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Train'),
        ),
    ]
